apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd
  namespace: team-a
  labels:
    app.kubernetes.io/name: nginx-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-argocd
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nginx-argocd
          image: public.ecr.aws/nginx/nginx-unprivileged:1.30.5
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-argocd
  namespace: team-a
  labels:
    app.kubernetes.io/name: nginx-argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-argocd
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-argocd
  namespace: team-a
  labels:
    app.kubernetes.io/name: nginx-argocd
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-argocd
                port:
                  number: 80
